name: 'Automated versioning'
description: 'vmn based, production grade solution for versioning agnostic to language. Full support for semantic versioning (Semver).'
branding:
  icon: trending-up
  color: green
inputs:
  app-name:
    description: "Name of the app to stamp"
    required: true
  do-stamp:
    type: boolean
    description: "Do you want to perform a stamp?"
    default: false
  stamp-mode:
    type: choice
    description: "Desired Stamp Mode"
    options:
      - major
      - minor
      - patch
    default: patch
  release-candidate: 
    type: boolean
    description: "Is it Release Candidate?"
  prerelease-name:
    type: string
    description: "Prerelease Name"
    default: rc
  release: 
    type: boolean
    description: "Is it ready to be released?"
  stamp_from_version:
    type: string
    description: "Overwrite the base that VMN stamp will work from"
  do-gen:
    type: boolean
    description: "Do you want to perform a generator?"
  gen-template-path:
    type: string
    description: "Jinja2 Template path"
  gen-output-path:
    type: string
    description: "Saving path"
  gen-custom-yaml-path:
    type: string
    description: "Customs params YAML file path"
  debug-mode:
    type: boolean
    description: "Show extra logs?"
  install-nonstable-vmn-version:
    type: boolean
    description: "Install nonstable vmn version?"
outputs:
  verstr:
    description: 'The version after stamping'
  dirty:
    description: 'Flag that indicate if the version is dirty (If changes have been made since last stamp operation)'
  is_in_rc_mode:
    description: 'Flag that indicate if the stamped app is in release candidate mode'
  verbose_yaml:
    description: 'The whole "vmn show --verbose <APP_NAME>" output'
runs:
  using: 'node16'
  main: 'dist/index.js'
