name: 'Automated versioning'
description: 'vmn based, production grade solution for versioning agnostic to language. Full support for semantic versioning (Semver).'
branding:
  icon: trending-up
  color: green
inputs:
  app-name:
    description: "Name of the app to stamp"
    required: true
  do-stamp:
    type: boolean
    description: "Do you want to perform a stamp?"
    default: false
  stamp-mode:
    type: choice
    description: "Desired Stamp Mode"
    options:
      - major
      - minor
      - patch
    default: patch
  release-candidate: 
    type: boolean
    description: "Is it Release Candidate?"
  prerelease-name:
    type: string
    description: "Prerelease Name"
    default: rc
  release: 
    type: boolean
    description: "Is it ready to be released?"
  stamp_from_version:
    type: string
    description: "Overwrite the base that VMN stamp will work from"
  debug-mode:
    type: boolean
    description: "Show extra logs?"
  install-nonstable-vmn-version:
    type: boolean
    description: "Install nonstable vmn version?"
outputs:
  verstr:
    description: 'The version after stamping'
runs:
  using: 'node16'
  main: 'dist/index.js'
